# frozen_string_literal: true

source "https://rubygems.org"

gem "faraday"
gem "rest-client"

gem "minitest", "~> 5.22"

gem "rake", "~> 13.2"
gem "webmock"

gem "pry", "~> 0.14.2"

gem "rubocop", "~> 1.63", require: false

gem "mocha", require: false
